spring.application.name=patient-management

server.port=${PORT:9090}

#db connection
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/patientmanagement	
spring.datasource.username=postgres
spring.datasource.password=123

#hibernate config
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# view resolver 
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
